// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: prove.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProveService_GetRunningProveTasks_FullMethodName = "/gnark_prover.ProveService/GetRunningProveTasks"
	ProveService_ProveTigaOffchain_FullMethodName    = "/gnark_prover.ProveService/ProveTigaOffchain"
	ProveService_ProveBinanceOffchain_FullMethodName = "/gnark_prover.ProveService/ProveBinanceOffchain"
	ProveService_ProveMerkleOffchain_FullMethodName  = "/gnark_prover.ProveService/ProveMerkleOffchain"
	ProveService_Ping_FullMethodName                 = "/gnark_prover.ProveService/Ping"
)

// ProveServiceClient is the client API for ProveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type ProveServiceClient interface {
	// Retrieves the number of currently running prove tasks
	GetRunningProveTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetRunningProveTasksResponse, error)
	ProveTigaOffchain(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponseV2, error)
	ProveBinanceOffchain(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponseV2, error)
	ProveMerkleOffchain(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponseV2, error)
	// Health check endpoint - returns pong response
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type proveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProveServiceClient(cc grpc.ClientConnInterface) ProveServiceClient {
	return &proveServiceClient{cc}
}

func (c *proveServiceClient) GetRunningProveTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetRunningProveTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunningProveTasksResponse)
	err := c.cc.Invoke(ctx, ProveService_GetRunningProveTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proveServiceClient) ProveTigaOffchain(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponseV2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveResponseV2)
	err := c.cc.Invoke(ctx, ProveService_ProveTigaOffchain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proveServiceClient) ProveBinanceOffchain(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponseV2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveResponseV2)
	err := c.cc.Invoke(ctx, ProveService_ProveBinanceOffchain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proveServiceClient) ProveMerkleOffchain(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponseV2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveResponseV2)
	err := c.cc.Invoke(ctx, ProveService_ProveMerkleOffchain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proveServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProveService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProveServiceServer is the server API for ProveService service.
// All implementations must embed UnimplementedProveServiceServer
// for forward compatibility.
//
// Service definition
type ProveServiceServer interface {
	// Retrieves the number of currently running prove tasks
	GetRunningProveTasks(context.Context, *Empty) (*GetRunningProveTasksResponse, error)
	ProveTigaOffchain(context.Context, *ProveRequest) (*ProveResponseV2, error)
	ProveBinanceOffchain(context.Context, *ProveRequest) (*ProveResponseV2, error)
	ProveMerkleOffchain(context.Context, *ProveRequest) (*ProveResponseV2, error)
	// Health check endpoint - returns pong response
	Ping(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedProveServiceServer()
}

// UnimplementedProveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProveServiceServer struct{}

func (UnimplementedProveServiceServer) GetRunningProveTasks(context.Context, *Empty) (*GetRunningProveTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunningProveTasks not implemented")
}
func (UnimplementedProveServiceServer) ProveTigaOffchain(context.Context, *ProveRequest) (*ProveResponseV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveTigaOffchain not implemented")
}
func (UnimplementedProveServiceServer) ProveBinanceOffchain(context.Context, *ProveRequest) (*ProveResponseV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveBinanceOffchain not implemented")
}
func (UnimplementedProveServiceServer) ProveMerkleOffchain(context.Context, *ProveRequest) (*ProveResponseV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveMerkleOffchain not implemented")
}
func (UnimplementedProveServiceServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedProveServiceServer) mustEmbedUnimplementedProveServiceServer() {}
func (UnimplementedProveServiceServer) testEmbeddedByValue()                      {}

// UnsafeProveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProveServiceServer will
// result in compilation errors.
type UnsafeProveServiceServer interface {
	mustEmbedUnimplementedProveServiceServer()
}

func RegisterProveServiceServer(s grpc.ServiceRegistrar, srv ProveServiceServer) {
	// If the following call pancis, it indicates UnimplementedProveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProveService_ServiceDesc, srv)
}

func _ProveService_GetRunningProveTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).GetRunningProveTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_GetRunningProveTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).GetRunningProveTasks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProveService_ProveTigaOffchain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).ProveTigaOffchain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_ProveTigaOffchain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).ProveTigaOffchain(ctx, req.(*ProveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProveService_ProveBinanceOffchain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).ProveBinanceOffchain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_ProveBinanceOffchain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).ProveBinanceOffchain(ctx, req.(*ProveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProveService_ProveMerkleOffchain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).ProveMerkleOffchain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_ProveMerkleOffchain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).ProveMerkleOffchain(ctx, req.(*ProveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProveService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ProveService_ServiceDesc is the grpc.ServiceDesc for ProveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gnark_prover.ProveService",
	HandlerType: (*ProveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRunningProveTasks",
			Handler:    _ProveService_GetRunningProveTasks_Handler,
		},
		{
			MethodName: "ProveTigaOffchain",
			Handler:    _ProveService_ProveTigaOffchain_Handler,
		},
		{
			MethodName: "ProveBinanceOffchain",
			Handler:    _ProveService_ProveBinanceOffchain_Handler,
		},
		{
			MethodName: "ProveMerkleOffchain",
			Handler:    _ProveService_ProveMerkleOffchain_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _ProveService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prove.proto",
}
