# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from modules.grpc_server import prove_service_pb2 as modules_dot_grpc__server_dot_prove__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in modules/grpc_server/prove_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ProveServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prove = channel.unary_unary(
                '/prove_service.ProveService/Prove',
                request_serializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveRequest.SerializeToString,
                response_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveResponse.FromString,
                _registered_method=True)
        self.ProveWithWitness = channel.unary_unary(
                '/prove_service.ProveService/ProveWithWitness',
                request_serializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveWithWitnessRequest.SerializeToString,
                response_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveWithWitnessResponse.FromString,
                _registered_method=True)
        self.ProveNosha256 = channel.unary_unary(
                '/prove_service.ProveService/ProveNosha256',
                request_serializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256Request.SerializeToString,
                response_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256Response.FromString,
                _registered_method=True)
        self.ProveNosha256WithWitness = channel.unary_unary(
                '/prove_service.ProveService/ProveNosha256WithWitness',
                request_serializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256WithWitnessRequest.SerializeToString,
                response_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256WithWitnessResponse.FromString,
                _registered_method=True)
        self.ProveNosha256Offchain = channel.unary_unary(
                '/prove_service.ProveService/ProveNosha256Offchain',
                request_serializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256OffchainRequest.SerializeToString,
                response_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256OffchainResponse.FromString,
                _registered_method=True)
        self.GetPublicKey = channel.unary_unary(
                '/prove_service.ProveService/GetPublicKey',
                request_serializer=modules_dot_grpc__server_dot_prove__service__pb2.Empty.SerializeToString,
                response_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.GetPublicKeyResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/prove_service.ProveService/Ping',
                request_serializer=modules_dot_grpc__server_dot_prove__service__pb2.Empty.SerializeToString,
                response_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.Empty.FromString,
                _registered_method=True)


class ProveServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Prove(self, request, context):
        """Generates a proof using the provided parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveWithWitness(self, request, context):
        """Generates a proof with witness
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveNosha256(self, request, context):
        """Processes the input without SHA256 and returns a proof
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveNosha256WithWitness(self, request, context):
        """Processes the input without SHA256 and returns a proof and witness
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveNosha256Offchain(self, request, context):
        """Processes the input without SHA256 and returns a proof and witness for offchain verify
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicKey(self, request, context):
        """Retrieves the public key for encrypting input data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Ping for health check or to keep the connection alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prove': grpc.unary_unary_rpc_method_handler(
                    servicer.Prove,
                    request_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveRequest.FromString,
                    response_serializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveResponse.SerializeToString,
            ),
            'ProveWithWitness': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveWithWitness,
                    request_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveWithWitnessRequest.FromString,
                    response_serializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveWithWitnessResponse.SerializeToString,
            ),
            'ProveNosha256': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveNosha256,
                    request_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256Request.FromString,
                    response_serializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256Response.SerializeToString,
            ),
            'ProveNosha256WithWitness': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveNosha256WithWitness,
                    request_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256WithWitnessRequest.FromString,
                    response_serializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256WithWitnessResponse.SerializeToString,
            ),
            'ProveNosha256Offchain': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveNosha256Offchain,
                    request_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256OffchainRequest.FromString,
                    response_serializer=modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256OffchainResponse.SerializeToString,
            ),
            'GetPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicKey,
                    request_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.Empty.FromString,
                    response_serializer=modules_dot_grpc__server_dot_prove__service__pb2.GetPublicKeyResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=modules_dot_grpc__server_dot_prove__service__pb2.Empty.FromString,
                    response_serializer=modules_dot_grpc__server_dot_prove__service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prove_service.ProveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prove_service.ProveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProveService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prove_service.ProveService/Prove',
            modules_dot_grpc__server_dot_prove__service__pb2.ProveRequest.SerializeToString,
            modules_dot_grpc__server_dot_prove__service__pb2.ProveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveWithWitness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prove_service.ProveService/ProveWithWitness',
            modules_dot_grpc__server_dot_prove__service__pb2.ProveWithWitnessRequest.SerializeToString,
            modules_dot_grpc__server_dot_prove__service__pb2.ProveWithWitnessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveNosha256(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prove_service.ProveService/ProveNosha256',
            modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256Request.SerializeToString,
            modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveNosha256WithWitness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prove_service.ProveService/ProveNosha256WithWitness',
            modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256WithWitnessRequest.SerializeToString,
            modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256WithWitnessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveNosha256Offchain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prove_service.ProveService/ProveNosha256Offchain',
            modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256OffchainRequest.SerializeToString,
            modules_dot_grpc__server_dot_prove__service__pb2.ProveNosha256OffchainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prove_service.ProveService/GetPublicKey',
            modules_dot_grpc__server_dot_prove__service__pb2.Empty.SerializeToString,
            modules_dot_grpc__server_dot_prove__service__pb2.GetPublicKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prove_service.ProveService/Ping',
            modules_dot_grpc__server_dot_prove__service__pb2.Empty.SerializeToString,
            modules_dot_grpc__server_dot_prove__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
