# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnark_prove.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gnark_prove.proto\x12\x0cgnark_prover\"+\n\x0cProveRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x0c\n\x04temp\x18\x02 \x01(\t\"\x9e\x01\n\x0fProveResponseV2\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\r\n\x05proof\x18\x03 \x01(\t\x12\x16\n\x0eproof_solidity\x18\x04 \x01(\t\x12\x13\n\x0bproof_bytes\x18\x05 \x01(\x0c\x12\x16\n\x0epublic_witness\x18\x06 \x01(\t\x12\x1c\n\x14public_witness_bytes\x18\x07 \x01(\x0c\"H\n\x1cGetRunningProveTasksResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty2\x8e\x03\n\x0cProveService\x12W\n\x14GetRunningProveTasks\x12\x13.gnark_prover.Empty\x1a*.gnark_prover.GetRunningProveTasksResponse\x12N\n\x11ProveTigaOffchain\x12\x1a.gnark_prover.ProveRequest\x1a\x1d.gnark_prover.ProveResponseV2\x12Q\n\x14ProveBinanceOffchain\x12\x1a.gnark_prover.ProveRequest\x1a\x1d.gnark_prover.ProveResponseV2\x12P\n\x13ProveMerkleOffchain\x12\x1a.gnark_prover.ProveRequest\x1a\x1d.gnark_prover.ProveResponseV2\x12\x30\n\x04Ping\x12\x13.gnark_prover.Empty\x1a\x13.gnark_prover.EmptyB\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gnark_prove_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001.'
  _globals['_PROVEREQUEST']._serialized_start=35
  _globals['_PROVEREQUEST']._serialized_end=78
  _globals['_PROVERESPONSEV2']._serialized_start=81
  _globals['_PROVERESPONSEV2']._serialized_end=239
  _globals['_GETRUNNINGPROVETASKSRESPONSE']._serialized_start=241
  _globals['_GETRUNNINGPROVETASKSRESPONSE']._serialized_end=313
  _globals['_EMPTY']._serialized_start=315
  _globals['_EMPTY']._serialized_end=322
  _globals['_PROVESERVICE']._serialized_start=325
  _globals['_PROVESERVICE']._serialized_end=723
# @@protoc_insertion_point(module_scope)
