# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import gnark_prove_pb2 as gnark__prove__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gnark_prove_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ProveServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRunningProveTasks = channel.unary_unary(
                '/gnark_prover.ProveService/GetRunningProveTasks',
                request_serializer=gnark__prove__pb2.Empty.SerializeToString,
                response_deserializer=gnark__prove__pb2.GetRunningProveTasksResponse.FromString,
                _registered_method=True)
        self.ProveTigaOffchain = channel.unary_unary(
                '/gnark_prover.ProveService/ProveTigaOffchain',
                request_serializer=gnark__prove__pb2.ProveRequest.SerializeToString,
                response_deserializer=gnark__prove__pb2.ProveResponseV2.FromString,
                _registered_method=True)
        self.ProveBinanceOffchain = channel.unary_unary(
                '/gnark_prover.ProveService/ProveBinanceOffchain',
                request_serializer=gnark__prove__pb2.ProveRequest.SerializeToString,
                response_deserializer=gnark__prove__pb2.ProveResponseV2.FromString,
                _registered_method=True)
        self.ProveMerkleOffchain = channel.unary_unary(
                '/gnark_prover.ProveService/ProveMerkleOffchain',
                request_serializer=gnark__prove__pb2.ProveRequest.SerializeToString,
                response_deserializer=gnark__prove__pb2.ProveResponseV2.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/gnark_prover.ProveService/Ping',
                request_serializer=gnark__prove__pb2.Empty.SerializeToString,
                response_deserializer=gnark__prove__pb2.Empty.FromString,
                _registered_method=True)


class ProveServiceServicer(object):
    """Service definition
    """

    def GetRunningProveTasks(self, request, context):
        """Retrieves the number of currently running prove tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveTigaOffchain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveBinanceOffchain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveMerkleOffchain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check endpoint - returns pong response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRunningProveTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunningProveTasks,
                    request_deserializer=gnark__prove__pb2.Empty.FromString,
                    response_serializer=gnark__prove__pb2.GetRunningProveTasksResponse.SerializeToString,
            ),
            'ProveTigaOffchain': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveTigaOffchain,
                    request_deserializer=gnark__prove__pb2.ProveRequest.FromString,
                    response_serializer=gnark__prove__pb2.ProveResponseV2.SerializeToString,
            ),
            'ProveBinanceOffchain': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveBinanceOffchain,
                    request_deserializer=gnark__prove__pb2.ProveRequest.FromString,
                    response_serializer=gnark__prove__pb2.ProveResponseV2.SerializeToString,
            ),
            'ProveMerkleOffchain': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveMerkleOffchain,
                    request_deserializer=gnark__prove__pb2.ProveRequest.FromString,
                    response_serializer=gnark__prove__pb2.ProveResponseV2.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=gnark__prove__pb2.Empty.FromString,
                    response_serializer=gnark__prove__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gnark_prover.ProveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gnark_prover.ProveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProveService(object):
    """Service definition
    """

    @staticmethod
    def GetRunningProveTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gnark_prover.ProveService/GetRunningProveTasks',
            gnark__prove__pb2.Empty.SerializeToString,
            gnark__prove__pb2.GetRunningProveTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveTigaOffchain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gnark_prover.ProveService/ProveTigaOffchain',
            gnark__prove__pb2.ProveRequest.SerializeToString,
            gnark__prove__pb2.ProveResponseV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveBinanceOffchain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gnark_prover.ProveService/ProveBinanceOffchain',
            gnark__prove__pb2.ProveRequest.SerializeToString,
            gnark__prove__pb2.ProveResponseV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveMerkleOffchain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gnark_prover.ProveService/ProveMerkleOffchain',
            gnark__prove__pb2.ProveRequest.SerializeToString,
            gnark__prove__pb2.ProveResponseV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gnark_prover.ProveService/Ping',
            gnark__prove__pb2.Empty.SerializeToString,
            gnark__prove__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
