// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: src/protobuf/prover.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProveService_Ping_FullMethodName                     = "/circom_prove.ProveService/Ping"
	ProveService_GetRunningProveTasks_FullMethodName     = "/circom_prove.ProveService/GetRunningProveTasks"
	ProveService_Prove_FullMethodName                    = "/circom_prove.ProveService/Prove"
	ProveService_ProveWithWitness_FullMethodName         = "/circom_prove.ProveService/ProveWithWitness"
	ProveService_ProveNosha256_FullMethodName            = "/circom_prove.ProveService/ProveNosha256"
	ProveService_ProveNosha256WithWitness_FullMethodName = "/circom_prove.ProveService/ProveNosha256WithWitness"
	ProveService_ProveNosha256Offchain_FullMethodName    = "/circom_prove.ProveService/ProveNosha256Offchain"
	ProveService_ProveV2_FullMethodName                  = "/circom_prove.ProveService/ProveV2"
)

// ProveServiceClient is the client API for ProveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type ProveServiceClient interface {
	// Ping method to check server health and get basic information
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error)
	// Retrieves the number of currently running prove tasks
	GetRunningProveTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetRunningProveTasksResponse, error)
	// Processes the input and returns a proof
	Prove(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponse, error)
	// Processes the input and returns both a proof and public witness data
	ProveWithWitness(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveWithWitnessResponse, error)
	// Processes the input without SHA256 verification and returns a proof
	ProveNosha256(ctx context.Context, in *ProveNosha256Request, opts ...grpc.CallOption) (*ProveNosha256Response, error)
	// Processes the input without SHA256 verification and returns both a proof and public witness data
	ProveNosha256WithWitness(ctx context.Context, in *ProveNosha256Request, opts ...grpc.CallOption) (*ProveNosha256WithWitnessResponse, error)
	// Processes the input without SHA256 verification and returns an off-chain proof and public witness data
	ProveNosha256Offchain(ctx context.Context, in *ProveNosha256Request, opts ...grpc.CallOption) (*ProveNosha256OffchainResponse, error)
	ProveV2(ctx context.Context, in *ProveNosha256Request, opts ...grpc.CallOption) (*ProveResponseV2, error)
}

type proveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProveServiceClient(cc grpc.ClientConnInterface) ProveServiceClient {
	return &proveServiceClient{cc}
}

func (c *proveServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, ProveService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proveServiceClient) GetRunningProveTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetRunningProveTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunningProveTasksResponse)
	err := c.cc.Invoke(ctx, ProveService_GetRunningProveTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proveServiceClient) Prove(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveResponse)
	err := c.cc.Invoke(ctx, ProveService_Prove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proveServiceClient) ProveWithWitness(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveWithWitnessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveWithWitnessResponse)
	err := c.cc.Invoke(ctx, ProveService_ProveWithWitness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proveServiceClient) ProveNosha256(ctx context.Context, in *ProveNosha256Request, opts ...grpc.CallOption) (*ProveNosha256Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveNosha256Response)
	err := c.cc.Invoke(ctx, ProveService_ProveNosha256_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proveServiceClient) ProveNosha256WithWitness(ctx context.Context, in *ProveNosha256Request, opts ...grpc.CallOption) (*ProveNosha256WithWitnessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveNosha256WithWitnessResponse)
	err := c.cc.Invoke(ctx, ProveService_ProveNosha256WithWitness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proveServiceClient) ProveNosha256Offchain(ctx context.Context, in *ProveNosha256Request, opts ...grpc.CallOption) (*ProveNosha256OffchainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveNosha256OffchainResponse)
	err := c.cc.Invoke(ctx, ProveService_ProveNosha256Offchain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proveServiceClient) ProveV2(ctx context.Context, in *ProveNosha256Request, opts ...grpc.CallOption) (*ProveResponseV2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveResponseV2)
	err := c.cc.Invoke(ctx, ProveService_ProveV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProveServiceServer is the server API for ProveService service.
// All implementations must embed UnimplementedProveServiceServer
// for forward compatibility.
//
// Service definition
type ProveServiceServer interface {
	// Ping method to check server health and get basic information
	Ping(context.Context, *Empty) (*PingResponse, error)
	// Retrieves the number of currently running prove tasks
	GetRunningProveTasks(context.Context, *Empty) (*GetRunningProveTasksResponse, error)
	// Processes the input and returns a proof
	Prove(context.Context, *ProveRequest) (*ProveResponse, error)
	// Processes the input and returns both a proof and public witness data
	ProveWithWitness(context.Context, *ProveRequest) (*ProveWithWitnessResponse, error)
	// Processes the input without SHA256 verification and returns a proof
	ProveNosha256(context.Context, *ProveNosha256Request) (*ProveNosha256Response, error)
	// Processes the input without SHA256 verification and returns both a proof and public witness data
	ProveNosha256WithWitness(context.Context, *ProveNosha256Request) (*ProveNosha256WithWitnessResponse, error)
	// Processes the input without SHA256 verification and returns an off-chain proof and public witness data
	ProveNosha256Offchain(context.Context, *ProveNosha256Request) (*ProveNosha256OffchainResponse, error)
	ProveV2(context.Context, *ProveNosha256Request) (*ProveResponseV2, error)
	mustEmbedUnimplementedProveServiceServer()
}

// UnimplementedProveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProveServiceServer struct{}

func (UnimplementedProveServiceServer) Ping(context.Context, *Empty) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedProveServiceServer) GetRunningProveTasks(context.Context, *Empty) (*GetRunningProveTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunningProveTasks not implemented")
}
func (UnimplementedProveServiceServer) Prove(context.Context, *ProveRequest) (*ProveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prove not implemented")
}
func (UnimplementedProveServiceServer) ProveWithWitness(context.Context, *ProveRequest) (*ProveWithWitnessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveWithWitness not implemented")
}
func (UnimplementedProveServiceServer) ProveNosha256(context.Context, *ProveNosha256Request) (*ProveNosha256Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveNosha256 not implemented")
}
func (UnimplementedProveServiceServer) ProveNosha256WithWitness(context.Context, *ProveNosha256Request) (*ProveNosha256WithWitnessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveNosha256WithWitness not implemented")
}
func (UnimplementedProveServiceServer) ProveNosha256Offchain(context.Context, *ProveNosha256Request) (*ProveNosha256OffchainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveNosha256Offchain not implemented")
}
func (UnimplementedProveServiceServer) ProveV2(context.Context, *ProveNosha256Request) (*ProveResponseV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveV2 not implemented")
}
func (UnimplementedProveServiceServer) mustEmbedUnimplementedProveServiceServer() {}
func (UnimplementedProveServiceServer) testEmbeddedByValue()                      {}

// UnsafeProveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProveServiceServer will
// result in compilation errors.
type UnsafeProveServiceServer interface {
	mustEmbedUnimplementedProveServiceServer()
}

func RegisterProveServiceServer(s grpc.ServiceRegistrar, srv ProveServiceServer) {
	// If the following call pancis, it indicates UnimplementedProveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProveService_ServiceDesc, srv)
}

func _ProveService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProveService_GetRunningProveTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).GetRunningProveTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_GetRunningProveTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).GetRunningProveTasks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProveService_Prove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).Prove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_Prove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).Prove(ctx, req.(*ProveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProveService_ProveWithWitness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).ProveWithWitness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_ProveWithWitness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).ProveWithWitness(ctx, req.(*ProveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProveService_ProveNosha256_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveNosha256Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).ProveNosha256(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_ProveNosha256_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).ProveNosha256(ctx, req.(*ProveNosha256Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProveService_ProveNosha256WithWitness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveNosha256Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).ProveNosha256WithWitness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_ProveNosha256WithWitness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).ProveNosha256WithWitness(ctx, req.(*ProveNosha256Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProveService_ProveNosha256Offchain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveNosha256Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).ProveNosha256Offchain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_ProveNosha256Offchain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).ProveNosha256Offchain(ctx, req.(*ProveNosha256Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProveService_ProveV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveNosha256Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProveServiceServer).ProveV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProveService_ProveV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProveServiceServer).ProveV2(ctx, req.(*ProveNosha256Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ProveService_ServiceDesc is the grpc.ServiceDesc for ProveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "circom_prove.ProveService",
	HandlerType: (*ProveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ProveService_Ping_Handler,
		},
		{
			MethodName: "GetRunningProveTasks",
			Handler:    _ProveService_GetRunningProveTasks_Handler,
		},
		{
			MethodName: "Prove",
			Handler:    _ProveService_Prove_Handler,
		},
		{
			MethodName: "ProveWithWitness",
			Handler:    _ProveService_ProveWithWitness_Handler,
		},
		{
			MethodName: "ProveNosha256",
			Handler:    _ProveService_ProveNosha256_Handler,
		},
		{
			MethodName: "ProveNosha256WithWitness",
			Handler:    _ProveService_ProveNosha256WithWitness_Handler,
		},
		{
			MethodName: "ProveNosha256Offchain",
			Handler:    _ProveService_ProveNosha256Offchain_Handler,
		},
		{
			MethodName: "ProveV2",
			Handler:    _ProveService_ProveV2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/protobuf/prover.proto",
}
