# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import circom_prove_pb2 as circom__prove__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in circom_prove_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ProveServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRunningProveTasks = channel.unary_unary(
                '/circom_prove.ProveService/GetRunningProveTasks',
                request_serializer=circom__prove__pb2.Empty.SerializeToString,
                response_deserializer=circom__prove__pb2.GetRunningProveTasksResponse.FromString,
                _registered_method=True)
        self.Prove = channel.unary_unary(
                '/circom_prove.ProveService/Prove',
                request_serializer=circom__prove__pb2.ProveRequest.SerializeToString,
                response_deserializer=circom__prove__pb2.ProveResponse.FromString,
                _registered_method=True)
        self.ProveWithWitness = channel.unary_unary(
                '/circom_prove.ProveService/ProveWithWitness',
                request_serializer=circom__prove__pb2.ProveRequest.SerializeToString,
                response_deserializer=circom__prove__pb2.ProveWithWitnessResponse.FromString,
                _registered_method=True)
        self.ProveNosha256 = channel.unary_unary(
                '/circom_prove.ProveService/ProveNosha256',
                request_serializer=circom__prove__pb2.ProveNosha256Request.SerializeToString,
                response_deserializer=circom__prove__pb2.ProveNosha256Response.FromString,
                _registered_method=True)
        self.ProveNosha256WithWitness = channel.unary_unary(
                '/circom_prove.ProveService/ProveNosha256WithWitness',
                request_serializer=circom__prove__pb2.ProveNosha256Request.SerializeToString,
                response_deserializer=circom__prove__pb2.ProveNosha256WithWitnessResponse.FromString,
                _registered_method=True)
        self.ProveNosha256Offchain = channel.unary_unary(
                '/circom_prove.ProveService/ProveNosha256Offchain',
                request_serializer=circom__prove__pb2.ProveNosha256Request.SerializeToString,
                response_deserializer=circom__prove__pb2.ProveNosha256OffchainResponse.FromString,
                _registered_method=True)
        self.ProveV2 = channel.unary_unary(
                '/circom_prove.ProveService/ProveV2',
                request_serializer=circom__prove__pb2.ProveNosha256Request.SerializeToString,
                response_deserializer=circom__prove__pb2.ProveResponseV2.FromString,
                _registered_method=True)


class ProveServiceServicer(object):
    """Service definition
    """

    def GetRunningProveTasks(self, request, context):
        """Retrieves the number of currently running prove tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prove(self, request, context):
        """Processes the input and returns a proof
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveWithWitness(self, request, context):
        """Processes the input and returns both a proof and public witness data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveNosha256(self, request, context):
        """Processes the input without SHA256 verification and returns a proof
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveNosha256WithWitness(self, request, context):
        """Processes the input without SHA256 verification and returns both a proof and public witness data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveNosha256Offchain(self, request, context):
        """Processes the input without SHA256 verification and returns an off-chain proof and public witness data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProveV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRunningProveTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunningProveTasks,
                    request_deserializer=circom__prove__pb2.Empty.FromString,
                    response_serializer=circom__prove__pb2.GetRunningProveTasksResponse.SerializeToString,
            ),
            'Prove': grpc.unary_unary_rpc_method_handler(
                    servicer.Prove,
                    request_deserializer=circom__prove__pb2.ProveRequest.FromString,
                    response_serializer=circom__prove__pb2.ProveResponse.SerializeToString,
            ),
            'ProveWithWitness': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveWithWitness,
                    request_deserializer=circom__prove__pb2.ProveRequest.FromString,
                    response_serializer=circom__prove__pb2.ProveWithWitnessResponse.SerializeToString,
            ),
            'ProveNosha256': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveNosha256,
                    request_deserializer=circom__prove__pb2.ProveNosha256Request.FromString,
                    response_serializer=circom__prove__pb2.ProveNosha256Response.SerializeToString,
            ),
            'ProveNosha256WithWitness': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveNosha256WithWitness,
                    request_deserializer=circom__prove__pb2.ProveNosha256Request.FromString,
                    response_serializer=circom__prove__pb2.ProveNosha256WithWitnessResponse.SerializeToString,
            ),
            'ProveNosha256Offchain': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveNosha256Offchain,
                    request_deserializer=circom__prove__pb2.ProveNosha256Request.FromString,
                    response_serializer=circom__prove__pb2.ProveNosha256OffchainResponse.SerializeToString,
            ),
            'ProveV2': grpc.unary_unary_rpc_method_handler(
                    servicer.ProveV2,
                    request_deserializer=circom__prove__pb2.ProveNosha256Request.FromString,
                    response_serializer=circom__prove__pb2.ProveResponseV2.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'circom_prove.ProveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('circom_prove.ProveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProveService(object):
    """Service definition
    """

    @staticmethod
    def GetRunningProveTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circom_prove.ProveService/GetRunningProveTasks',
            circom__prove__pb2.Empty.SerializeToString,
            circom__prove__pb2.GetRunningProveTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circom_prove.ProveService/Prove',
            circom__prove__pb2.ProveRequest.SerializeToString,
            circom__prove__pb2.ProveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveWithWitness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circom_prove.ProveService/ProveWithWitness',
            circom__prove__pb2.ProveRequest.SerializeToString,
            circom__prove__pb2.ProveWithWitnessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveNosha256(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circom_prove.ProveService/ProveNosha256',
            circom__prove__pb2.ProveNosha256Request.SerializeToString,
            circom__prove__pb2.ProveNosha256Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveNosha256WithWitness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circom_prove.ProveService/ProveNosha256WithWitness',
            circom__prove__pb2.ProveNosha256Request.SerializeToString,
            circom__prove__pb2.ProveNosha256WithWitnessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveNosha256Offchain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circom_prove.ProveService/ProveNosha256Offchain',
            circom__prove__pb2.ProveNosha256Request.SerializeToString,
            circom__prove__pb2.ProveNosha256OffchainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProveV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circom_prove.ProveService/ProveV2',
            circom__prove__pb2.ProveNosha256Request.SerializeToString,
            circom__prove__pb2.ProveResponseV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
