CLI_LOGGER = "cli"
PROVE_SERVICE_LOGGER = "prove_service"

PROVER_CIRCOM = 'circom'
PROVER_PRIVATE = 'private'

PUBLIC_KEY = "public_key"
PRIVATE_KEY = "private_key"

STATUS_CODE_SUCCESSFULLY = 0
STATUS_CODE_ERROR = -1

STATUS_CODE_TASK_NOT_FOUND = 1000
STATUS_CODE_TASK_INVALID = 1001
STATUS_CODE_UNSUPPORT_TASK_TYPE = 1002
STATUS_CODE_UNSUPPORT_PROVER = 1003
STATUS_CODE_UNSUPPORT_OAUTH_PROVIDER = 1004
STATUS_CODE_UNAUTHORIZED_PAYLOAD = 1005
STATUS_CODE_PROVER_NOT_RESPONSE = 1006


STATUS_CODE_PUBLIC_KEY_NOT_FOUND = 2000
STATUS_CODE_PUBLIC_KEY_INVALID = 2001
STATUS_CODE_PRIVATE_KEY_NOT_FOUND = 2002
STATUS_CODE_PRIVATE_KEY_INVALID = 2003





OAUTH_PROVIDER_GOOGLE = "google"
OAUTH_PROVIDER_X509_GOOGLE= "x509_google"
OAUTH_PROVIDER_TELEGRAM = "telegram"

TASK_TYPE_ZKLOGIN = 0
TASK_TYPE_TIGA = -1

TASK_STATUS_PENGDING = 0
TASK_STATUS_RUNNING = 1