# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: private_prove.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13private_prove.proto\x12\rprivate_prove\"+\n\x0cProveRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x0c\n\x04temp\x18\x02 \x01(\t\"\x9e\x01\n\x0fProveResponseV2\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\r\n\x05proof\x18\x03 \x01(\t\x12\x16\n\x0eproof_solidity\x18\x04 \x01(\t\x12\x13\n\x0bproof_bytes\x18\x05 \x01(\x0c\x12\x16\n\x0epublic_witness\x18\x06 \x01(\t\x12\x1c\n\x14public_witness_bytes\x18\x07 \x01(\x0c\"H\n\x1cGetRunningProveTasksResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty2\xe4\x02\n\x0cProveService\x12Y\n\x14GetRunningProveTasks\x12\x14.private_prove.Empty\x1a+.private_prove.GetRunningProveTasksResponse\x12P\n\x11ProveTigaOffchain\x12\x1b.private_prove.ProveRequest\x1a\x1e.private_prove.ProveResponseV2\x12S\n\x14ProveBinanceOffchain\x12\x1b.private_prove.ProveRequest\x1a\x1e.private_prove.ProveResponseV2\x12R\n\x13ProveMerkleOffchain\x12\x1b.private_prove.ProveRequest\x1a\x1e.private_prove.ProveResponseV2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'private_prove_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROVEREQUEST']._serialized_start=38
  _globals['_PROVEREQUEST']._serialized_end=81
  _globals['_PROVERESPONSEV2']._serialized_start=84
  _globals['_PROVERESPONSEV2']._serialized_end=242
  _globals['_GETRUNNINGPROVETASKSRESPONSE']._serialized_start=244
  _globals['_GETRUNNINGPROVETASKSRESPONSE']._serialized_end=316
  _globals['_EMPTY']._serialized_start=318
  _globals['_EMPTY']._serialized_end=325
  _globals['_PROVESERVICE']._serialized_start=328
  _globals['_PROVESERVICE']._serialized_end=684
# @@protoc_insertion_point(module_scope)
