# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prove_service_v2.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16prove_service_v2.proto\x12\x10prove_service.v2\x1a\x1bgoogle/protobuf/empty.proto\"\xcd\x01\n\x14GenerateProofRequest\x12\x0e\n\x06prover\x18\x01 \x01(\t\x12\x1b\n\x13\x63ircuit_template_id\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x0e\n\x06length\x18\x04 \x01(\x05\x12\x14\n\x0cis_encrypted\x18\x05 \x01(\x08\x12\x12\n\nauth_token\x18\x06 \x01(\t\x12\x11\n\ttask_type\x18\x07 \x01(\x05\x12\x16\n\x0eoauth_provider\x18\x08 \x01(\t\x12\x12\n\nproof_hash\x18\t \x01(\t\"\xa4\x01\n\x15GenerateProofResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\r\n\x05proof\x18\x03 \x01(\t\x12\x16\n\x0eproof_solidity\x18\x04 \x01(\t\x12\x13\n\x0bproof_bytes\x18\x05 \x01(\x0c\x12\x16\n\x0epublic_witness\x18\x06 \x01(\t\x12\x1c\n\x14public_witness_bytes\x18\x07 \x01(\x0c\"E\n\x14GetPublicKeyResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x12\n\npublic_key\x18\x03 \x01(\t2\xf0\x01\n\x0cProveService\x12X\n\x05Prove\x12&.prove_service.v2.GenerateProofRequest\x1a\'.prove_service.v2.GenerateProofResponse\x12N\n\x0cGetPublicKey\x12\x16.google.protobuf.Empty\x1a&.prove_service.v2.GetPublicKeyResponse\x12\x36\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prove_service_v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEPROOFREQUEST']._serialized_start=74
  _globals['_GENERATEPROOFREQUEST']._serialized_end=279
  _globals['_GENERATEPROOFRESPONSE']._serialized_start=282
  _globals['_GENERATEPROOFRESPONSE']._serialized_end=446
  _globals['_GETPUBLICKEYRESPONSE']._serialized_start=448
  _globals['_GETPUBLICKEYRESPONSE']._serialized_end=517
  _globals['_PROVESERVICE']._serialized_start=520
  _globals['_PROVESERVICE']._serialized_end=760
# @@protoc_insertion_point(module_scope)
